apiVersion: v1
kind: Pod

metadata: 
  name: "mysql"
  labels: 
     app: web
spec:
  containers:
  - name: "mydb"
    image: "mysql:5.7"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: redhat

    - name: MYSQL_USER
      value: abhi

    - name: MYSQL_PASS
      value: redhat

    - name: MYSQL_DATABASE
      value: wp